import "./globals.css";
import "./styles.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Star Bucks Coffee company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="text-">
      <body className="font-sans">{children}</body>
    </html>
  );
}
